# Generated by Django 4.1.2 on 2022-10-08 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mentor", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Events",
            new_name="Event",
        ),
    ]
