# Generated by Django 4.1.2 on 2022-10-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentordata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre', max_length=100)),
                ('title', models.CharField(help_text='Título', max_length=100)),
                ('text', models.TextField(help_text='Texto del testimonio')),
                ('image', models.ImageField(upload_to='projects')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Nombre', max_length=100)),
                ('last_name', models.CharField(help_text='Apellido', max_length=100)),
                ('title', models.CharField(help_text='Título', max_length=100)),
                ('brief', models.TextField(help_text='Resumen curricular')),
                ('photo', models.ImageField(help_text='Foto', upload_to='projects')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='text',
            field=models.TextField(help_text='Resumen del evento'),
        ),
    ]
