# Generated by Django 4.1.2 on 2022-10-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentordata", "0003_testimonial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonial",
            name="text",
            field=models.TextField(help_text="Texto del testimonio"),
        ),
    ]
