# Generated by Django 4.1.2 on 2022-10-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentordata", "0004_alter_testimonial_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="text",
            field=models.TextField(help_text="Resumen del evento"),
        ),
        migrations.AlterField(
            model_name="trainer",
            name="brief",
            field=models.TextField(help_text="Resumen curricular"),
        ),
    ]
